"""
유튜브 검색 키워드 데이터베이스
구조: (언어, 키워드, 메인카테고리, 서브카테고리)
"""

KEYWORDS = [
    # ══════════════════════════════════════════════════════════════
    # 가족여행 (Family Travel)
    # ══════════════════════════════════════════════════════════════
    ("🇰🇷 한국어",           "가족 한국여행",                  "가족여행", "일반"),
    ("🇰🇷 한국어",           "가족 서울여행 브이로그",           "가족여행", "브이로그"),
    ("🇰🇷 한국어",           "외국인 가족 한국여행",             "가족여행", "외국인"),
    ("🇰🇷 한국어",           "부모님과 한국여행",               "가족여행", "부모님"),
    ("🇰🇷 한국어",           "아이와 한국여행",                 "가족여행", "아이"),
    ("🇰🇷 한국어",           "제주도 가족여행",                 "가족여행", "지역"),
    ("🇺🇸 English",         "korea family vlog",              "가족여행", "브이로그"),
    ("🇺🇸 English",         "family trip to korea",           "가족여행", "일반"),
    ("🇺🇸 English",         "seoul family vlog",              "가족여행", "브이로그"),
    ("🇺🇸 English",         "korea with kids",                "가족여행", "아이"),
    ("🇺🇸 English",         "korea with family",              "가족여행", "일반"),
    ("🇺🇸 English",         "family travel korea",            "가족여행", "일반"),
    ("🇺🇸 English",         "korea trip with parents",        "가족여행", "부모님"),
    ("🇺🇸 English",         "family vacation korea",          "가족여행", "일반"),
    ("🇺🇸 English",         "traveling to korea with family", "가족여행", "일반"),
    ("🇺🇸 English",         "korea family itinerary",         "가족여행", "일정"),
    ("🇺🇸 English",         "jeju family trip",               "가족여행", "지역"),
    ("🇺🇸 English",         "busan with family",              "가족여행", "지역"),
    ("🇫🇷 Français",        "voyage en famille corée",        "가족여행", "일반"),
    ("🇫🇷 Français",        "vlog famille corée",             "가족여행", "브이로그"),
    ("🇫🇷 Français",        "séoul en famille",               "가족여행", "지역"),
    ("🇫🇷 Français",        "corée du sud en famille",        "가족여행", "일반"),
    ("🇫🇷 Français",        "voyage corée avec enfants",      "가족여행", "아이"),
    ("🇧🇷 Português",       "viagem em família coreia",       "가족여행", "일반"),
    ("🇧🇷 Português",       "coreia em família",              "가족여행", "일반"),
    ("🇧🇷 Português",       "vlog família coreia",            "가족여행", "브이로그"),
    ("🇧🇷 Português",       "viagem para coreia com filhos",  "가족여행", "아이"),
    ("🇧🇷 Português",       "seul com a família",             "가족여행", "지역"),
    ("🇪🇸 Español",         "viaje en familia a corea",       "가족여행", "일반"),
    ("🇪🇸 Español",         "corea en familia",               "가족여행", "일반"),
    ("🇪🇸 Español",         "vlog familiar corea",            "가족여행", "브이로그"),
    ("🇪🇸 Español",         "seúl con niños",                 "가족여행", "아이"),
    ("🇯🇵 日本語",           "韓国 家族旅行",                  "가족여행", "일반"),
    ("🇯🇵 日本語",           "家族で韓国旅行",                  "가족여행", "일반"),
    ("🇯🇵 日本語",           "韓国旅行 子連れ",                 "가족여행", "아이"),
    ("🇯🇵 日本語",           "親子 韓国旅行",                   "가족여행", "부모님/아이"),
    ("🇯🇵 日本語",           "ソウル 家族旅行",                 "가족여행", "지역"),
    ("🇯🇵 日本語",           "家族vlog 韓国",                   "가족여행", "브이로그"),
    ("🇨🇳 中文",            "韓國親子旅遊",                    "가족여행", "아이"),
    ("🇨🇳 中文",            "首爾親子自由行",                   "가족여행", "지역"),
    ("🇨🇳 中文",            "家庭旅遊 韓國",                   "가족여행", "일반"),
    ("🇨🇳 中文",            "帶小孩去韓國",                    "가족여행", "아이"),
    ("🇩🇪 Deutsch",         "familienurlaub korea",           "가족여행", "일반"),
    ("🇩🇪 Deutsch",         "korea mit kindern",              "가족여행", "아이"),
    ("🇩🇪 Deutsch",         "familienreise südkorea",         "가족여행", "일반"),
    ("🇩🇪 Deutsch",         "korea familie vlog",             "가족여행", "브이로그"),
    ("🇻🇳 Tiếng Việt",      "du lịch hàn quốc gia đình",     "가족여행", "일반"),
    ("🇻🇳 Tiếng Việt",      "vlog gia đình hàn quốc",        "가족여행", "브이로그"),
    ("🇻🇳 Tiếng Việt",      "đưa con đi hàn quốc",           "가족여행", "아이"),
    ("🇹🇭 ภาษาไทย",         "เที่ยวเกาหลีครอบครัว",           "가족여행", "일반"),
    ("🇹🇭 ภาษาไทย",         "พาครอบครัวเที่ยวเกาหลี",         "가족여행", "일반"),
    ("🇮🇩 Bahasa Indonesia", "liburan keluarga ke korea",     "가족여행", "일반"),
    ("🇮🇩 Bahasa Indonesia", "vlog keluarga korea",           "가족여행", "브이로그"),
    ("🇷🇺 Русский",          "семейное путешествие в корею",  "가족여행", "일반"),
    ("🇷🇺 Русский",          "корея с детьми",                "가족여행", "아이"),
    ("🇷🇺 Русский",          "семейный влог корея",           "가족여행", "브이로그"),
    ("🇮🇳 हिन्दी",           "कोरिया फैमिली ट्रिप",           "가족여행", "일반"),
    ("🇮🇳 हिन्दी",           "बच्चों के साथ कोरिया यात्रा",   "가족여행", "아이"),
    ("🇸🇦 العربية",          "رحلة عائلية إلى كوريا",         "가족여행", "일반"),
    ("🇸🇦 العربية",          "كوريا مع العائلة",              "가족여행", "일반"),
    ("🇹🇷 Türkçe",           "kore aile tatili",              "가족여행", "일반"),
    ("🇵🇱 Polski",           "rodzinne wakacje korea",        "가족여행", "일반"),
    ("🇵🇱 Polski",           "korea z dziećmi",               "가족여행", "아이"),
    ("🇳🇱 Nederlands",       "gezinsvakantie korea",          "가족여행", "일반"),
    ("🇳🇱 Nederlands",       "korea met kinderen",            "가족여행", "아이"),
    ("🇮🇹 Italiano",         "viaggio in famiglia corea",     "가족여행", "일반"),
    ("🇮🇹 Italiano",         "corea del sud con bambini",     "가족여행", "아이"),
    ("🇸🇪 Svenska",          "familjesemester korea",         "가족여행", "일반"),
    ("🇩🇰 Dansk",            "familieferie korea",            "가족여행", "일반"),
    ("🇳🇴 Norsk",            "familieferie korea",            "가족여행", "일반"),
    ("🇫🇮 Suomi",            "perheloma korea",               "가족여행", "일반"),
    ("🇲🇾 Bahasa Melayu",    "percutian keluarga ke korea",   "가족여행", "일반"),
    ("🇵🇭 Tagalog",          "pamilya sa korea",              "가족여행", "일반"),
    ("🇲🇳 Монгол",           "гэр бүлээрээ солонгост аялах",  "가족여행", "일반"),
    ("🇺🇦 Українська",       "сімейна подорож до кореї",      "가족여행", "일반"),

    # ══════════════════════════════════════════════════════════════
    # 홀로/커플/신혼 여행 (Solo / Couple / Honeymoon)
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "korea solo travel",               "홀로/커플/신혼", "홀로여행"),
    ("🇺🇸 English",  "solo trip korea vlog",            "홀로/커플/신혼", "홀로여행"),
    ("🇺🇸 English",  "traveling korea alone",           "홀로/커플/신혼", "홀로여행"),
    ("🇺🇸 English",  "solo female travel korea",        "홀로/커플/신혼", "홀로여행"),
    ("🇺🇸 English",  "korea couple trip",               "홀로/커플/신혼", "커플여행"),
    ("🇺🇸 English",  "couple vlog korea",               "홀로/커플/신혼", "커플여행"),
    ("🇺🇸 English",  "korea honeymoon",                 "홀로/커플/신혼", "신혼여행"),
    ("🇺🇸 English",  "honeymoon in korea vlog",         "홀로/커플/신혼", "신혼여행"),
    ("🇺🇸 English",  "romantic honeymoon seoul",        "홀로/커플/신혼", "신혼여행"),
    ("🇯🇵 日本語",    "韓国 一人旅",                     "홀로/커플/신혼", "홀로여행"),
    ("🇯🇵 日本語",    "ソウル 一人旅 女子",               "홀로/커플/신혼", "홀로여행"),
    ("🇯🇵 日本語",    "韓国 カップル旅行",                "홀로/커플/신혼", "커플여행"),
    ("🇯🇵 日本語",    "韓国 新婚旅行",                   "홀로/커플/신혼", "신혼여행"),
    ("🇨🇳 中文",     "韓國自由行",                       "홀로/커플/신혼", "홀로여행"),
    ("🇨🇳 中文",     "一個人去韓國",                     "홀로/커플/신혼", "홀로여행"),
    ("🇨🇳 中文",     "韓國情侶旅行",                     "홀로/커플/신혼", "커플여행"),
    ("🇨🇳 中文",     "韓國蜜月旅行",                     "홀로/커플/신혼", "신혼여행"),
    ("🇫🇷 Français", "voyage corée seul",               "홀로/커플/신혼", "홀로여행"),
    ("🇫🇷 Français", "corée en couple",                 "홀로/커플/신혼", "커플여행"),
    ("🇫🇷 Français", "lune de miel corée",              "홀로/커플/신혼", "신혼여행"),
    ("🇪🇸 Español",  "viajar solo a corea",             "홀로/커플/신혼", "홀로여행"),
    ("🇪🇸 Español",  "viaje en pareja corea",           "홀로/커플/신혼", "커플여행"),
    ("🇪🇸 Español",  "luna de miel corea",              "홀로/커플/신혼", "신혼여행"),
    ("🇧🇷 Português", "viajando sozinho coreia",        "홀로/커플/신혼", "홀로여행"),
    ("🇧🇷 Português", "viagem casal coreia",            "홀로/커플/신혼", "커플여행"),
    ("🇧🇷 Português", "lua de mel coreia",              "홀로/커플/신혼", "신혼여행"),
    ("🇩🇪 Deutsch",  "korea alleine reisen",            "홀로/커플/신혼", "홀로여행"),
    ("🇩🇪 Deutsch",  "korea paarurlaub",                "홀로/커플/신혼", "커플여행"),
    ("🇩🇪 Deutsch",  "flitterwochen korea",             "홀로/커플/신혼", "신혼여행"),
    ("🇷🇺 Русский",  "корея одному",                    "홀로/커플/신혼", "홀로여행"),
    ("🇷🇺 Русский",  "корея для пар",                   "홀로/커플/신혼", "커플여행"),
    ("🇷🇺 Русский",  "медовый месяц корея",             "홀로/커플/신혼", "신혼여행"),
    ("🇮🇳 हिन्दी",   "अकेले कोरिया यात्रा",             "홀로/커플/신혼", "홀로여행"),
    ("🇮🇳 हिन्दी",   "कोरिया हनीमून",                   "홀로/커플/신혼", "신혼여행"),
    ("🇻🇳 Tiếng Việt","du lịch hàn quốc một mình",     "홀로/커플/신혼", "홀로여행"),
    ("🇻🇳 Tiếng Việt","du lịch hàn quốc cặp đôi",      "홀로/커플/신혼", "커플여행"),
    ("🇻🇳 Tiếng Việt","tuần trăng mật hàn quốc",       "홀로/커플/신혼", "신혼여행"),
    ("🇹🇭 ภาษาไทย",  "เที่ยวเกาหลีคนเดียว",             "홀로/커플/신혼", "홀로여행"),
    ("🇹🇭 ภาษาไทย",  "เที่ยวเกาหลีคู่รัก",              "홀로/커플/신혼", "커플여행"),
    ("🇹🇭 ภาษาไทย",  "ฮันนีมูนเกาหลี",                  "홀로/커플/신혼", "신혼여행"),
    ("🇮🇩 Bahasa Indonesia","jalan jalan korea sendiri", "홀로/커플/신혼", "홀로여행"),
    ("🇮🇩 Bahasa Indonesia","korea trip couple",         "홀로/커플/신혼", "커플여행"),
    ("🇮🇩 Bahasa Indonesia","bulan madu korea",          "홀로/커플/신혼", "신혼여행"),
    ("🇸🇦 العربية",   "السفر وحيدا إلى كوريا",          "홀로/커플/신혼", "홀로여행"),
    ("🇸🇦 العربية",   "شهر العسل كوريا",                "홀로/커플/신혼", "신혼여행"),
    ("🇹🇷 Türkçe",   "kore yalnız seyahat",             "홀로/커플/신혼", "홀로여행"),
    ("🇹🇷 Türkçe",   "kore balayı",                     "홀로/커플/신혼", "신혼여행"),
    ("🇵🇱 Polski",   "korea samotna podróż",            "홀로/커플/신혼", "홀로여행"),
    ("🇵🇱 Polski",   "miesiąc miodowy korea",           "홀로/커플/신혼", "신혼여행"),
    ("🇮🇹 Italiano", "viaggio da solo corea",           "홀로/커플/신혼", "홀로여행"),
    ("🇮🇹 Italiano", "luna di miele corea",             "홀로/커플/신혼", "신혼여행"),
    ("🇳🇱 Nederlands","korea alleen reizen",            "홀로/커플/신혼", "홀로여행"),
    ("🇳🇱 Nederlands","huwelijksreis korea",            "홀로/커플/신혼", "신혼여행"),
    ("🇸🇪 Svenska",  "resa ensam korea",                "홀로/커플/신혼", "홀로여행"),
    ("🇸🇪 Svenska",  "bröllopsresa korea",              "홀로/커플/신혼", "신혼여행"),
    ("🇺🇦 Українська","сімейний влог корея",            "홀로/커플/신혼", "일반"),

    # ══════════════════════════════════════════════════════════════
    # 특수 여행 유형 (Cycling / Backpacking / Road Trip / Hiking / etc.)
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "cycling korea",                   "특수여행유형", "자전거"),
    ("🇺🇸 English",  "bike touring korea",              "특수여행유형", "자전거"),
    ("🇺🇸 English",  "4 rivers bike path korea",        "특수여행유형", "자전거"),
    ("🇺🇸 English",  "korea cycling vlog",              "특수여행유형", "자전거"),
    ("🇺🇸 English",  "korea backpacking",               "특수여행유형", "배낭여행"),
    ("🇺🇸 English",  "budget travel korea",             "특수여행유형", "배낭여행"),
    ("🇺🇸 English",  "korea road trip",                 "특수여행유형", "자동차"),
    ("🇺🇸 English",  "driving in korea vlog",           "특수여행유형", "자동차"),
    ("🇺🇸 English",  "road trip seoul to busan",        "특수여행유형", "자동차"),
    ("🇺🇸 English",  "korea hiking trip",               "특수여행유형", "등산/하이킹"),
    ("🇺🇸 English",  "hiking in korea vlog",            "특수여행유형", "등산/하이킹"),
    ("🇺🇸 English",  "hallasan hike vlog",              "특수여행유형", "등산/하이킹"),
    ("🇺🇸 English",  "korea mountain trail",            "특수여행유형", "등산/하이킹"),
    ("🇺🇸 English",  "korea temple stay",               "특수여행유형", "템플스테이"),
    ("🇺🇸 English",  "temple stay experience korea",    "특수여행유형", "템플스테이"),
    ("🇺🇸 English",  "korean street food tour",         "특수여행유형", "먹방여행"),
    ("🇺🇸 English",  "eating my way through korea",     "특수여행유형", "먹방여행"),
    ("🇺🇸 English",  "korea winter trip",               "특수여행유형", "계절여행"),
    ("🇺🇸 English",  "korea cherry blossom trip",       "특수여행유형", "계절여행"),
    ("🇺🇸 English",  "autumn korea travel",             "특수여행유형", "계절여행"),
    ("🇺🇸 English",  "first time in korea",             "특수여행유형", "첫방문"),
    ("🇺🇸 English",  "foreigner first korea trip",      "특수여행유형", "첫방문"),
    ("🇯🇵 日本語",    "韓国 自転車旅",                   "특수여행유형", "자전거"),
    ("🇯🇵 日本語",    "韓国 バックパッカー",              "특수여행유형", "배낭여행"),
    ("🇯🇵 日本語",    "韓国 ドライブ旅行",               "특수여행유형", "자동차"),
    ("🇯🇵 日本語",    "韓国 登山",                       "특수여행유형", "등산/하이킹"),
    ("🇯🇵 日本語",    "漢拏山 登山 vlog",                "특수여행유형", "등산/하이킹"),
    ("🇯🇵 日本語",    "韓国 テンプルステイ",              "특수여행유형", "템플스테이"),
    ("🇯🇵 日本語",    "韓国 屋台 食べ歩き",              "특수여행유형", "먹방여행"),
    ("🇯🇵 日本語",    "韓国 冬旅行",                     "특수여행유형", "계절여행"),
    ("🇯🇵 日本語",    "韓国 桜 旅行",                    "특수여행유형", "계절여행"),
    ("🇯🇵 日本語",    "初めての韓国旅行",                 "특수여행유형", "첫방문"),
    ("🇨🇳 中文",     "韓國騎自行車",                     "특수여행유형", "자전거"),
    ("🇨🇳 中文",     "韓國背包客",                       "특수여행유형", "배낭여행"),
    ("🇨🇳 中文",     "韓國自駕遊",                       "특수여행유형", "자동차"),
    ("🇨🇳 中文",     "韓國登山",                         "특수여행유형", "등산/하이킹"),
    ("🇨🇳 中文",     "韓國寺廟住宿",                     "특수여행유형", "템플스테이"),
    ("🇨🇳 中文",     "韓國街頭美食",                     "특수여행유형", "먹방여행"),
    ("🇨🇳 中文",     "韓國冬天旅行",                     "특수여행유형", "계절여행"),
    ("🇨🇳 中文",     "韓國櫻花季旅行",                   "특수여행유형", "계절여행"),
    ("🇨🇳 中文",     "第一次去韓國",                     "특수여행유형", "첫방문"),
    ("🇫🇷 Français", "vélo en corée",                   "특수여행유형", "자전거"),
    ("🇫🇷 Français", "backpack corée",                  "특수여행유형", "배낭여행"),
    ("🇫🇷 Français", "road trip corée",                 "특수여행유형", "자동차"),
    ("🇫🇷 Français", "randonnée corée",                 "특수여행유형", "등산/하이킹"),
    ("🇫🇷 Français", "séjour temple corée",             "특수여행유형", "템플스테이"),
    ("🇫🇷 Français", "street food corée",               "특수여행유형", "먹방여행"),
    ("🇫🇷 Français", "corée en hiver",                  "특수여행유형", "계절여행"),
    ("🇫🇷 Français", "premier voyage corée",            "특수여행유형", "첫방문"),
    ("🇪🇸 Español",  "bicicleta corea del sur",         "특수여행유형", "자전거"),
    ("🇪🇸 Español",  "mochilero corea",                 "특수여행유형", "배낭여행"),
    ("🇪🇸 Español",  "road trip corea",                 "특수여행유형", "자동차"),
    ("🇪🇸 Español",  "senderismo corea",                "특수여행유형", "등산/하이킹"),
    ("🇪🇸 Español",  "comida callejera corea",          "특수여행유형", "먹방여행"),
    ("🇪🇸 Español",  "corea en invierno",               "특수여행유형", "계절여행"),
    ("🇪🇸 Español",  "primer viaje a corea",            "특수여행유형", "첫방문"),
    ("🇧🇷 Português", "bicicleta coreia do sul",        "특수여행유형", "자전거"),
    ("🇧🇷 Português", "mochilão coreia",                "특수여행유형", "배낭여행"),
    ("🇧🇷 Português", "road trip coreia",               "특수여행유형", "자동차"),
    ("🇧🇷 Português", "trilha coreia",                  "특수여행유형", "등산/하이킹"),
    ("🇧🇷 Português", "comida de rua coreia",           "특수여행유형", "먹방여행"),
    ("🇧🇷 Português", "primeira vez coreia",            "특수여행유형", "첫방문"),
    ("🇩🇪 Deutsch",  "fahrradtour korea",               "특수여행유형", "자전거"),
    ("🇩🇪 Deutsch",  "backpacking korea",               "특수여행유형", "배낭여행"),
    ("🇩🇪 Deutsch",  "roadtrip korea",                  "특수여행유형", "자동차"),
    ("🇩🇪 Deutsch",  "wandern korea",                   "특수여행유형", "등산/하이킹"),
    ("🇩🇪 Deutsch",  "street food korea",               "특수여행유형", "먹방여행"),
    ("🇩🇪 Deutsch",  "korea im winter",                 "특수여행유형", "계절여행"),
    ("🇩🇪 Deutsch",  "erste reise korea",               "특수여행유형", "첫방문"),
    ("🇷🇺 Русский",  "велопутешествие корея",            "특수여행유형", "자전거"),
    ("🇷🇺 Русский",  "бэкпекинг корея",                 "특수여행유형", "배낭여행"),
    ("🇷🇺 Русский",  "автопутешествие корея",            "특수여행유형", "자동차"),
    ("🇷🇺 Русский",  "пеший туризм корея",              "특수여행유형", "등산/하이킹"),
    ("🇷🇺 Русский",  "уличная еда корея",               "특수여행유형", "먹방여행"),
    ("🇷🇺 Русский",  "корея зимой",                     "특수여행유형", "계절여행"),
    ("🇷🇺 Русский",  "первая поездка корея",            "특수여행유형", "첫방문"),
    ("🇮🇳 हिन्दी",   "कोरिया साइकिल ट्रिप",             "특수여행유형", "자전거"),
    ("🇮🇳 हिन्दी",   "कोरिया रोड ट्रिप",               "특수여행유형", "자동차"),
    ("🇮🇳 हिन्दी",   "कोरिया ट्रैकिंग",                "특수여행유형", "등산/하이킹"),
    ("🇮🇳 हिन्दी",   "कोरिया स्ट्रीट फूड",              "특수여행유형", "먹방여행"),
    ("🇻🇳 Tiếng Việt","đạp xe hàn quốc",               "특수여행유형", "자전거"),
    ("🇻🇳 Tiếng Việt","leo núi hàn quốc",              "특수여행유형", "등산/하이킹"),
    ("🇻🇳 Tiếng Việt","ẩm thực đường phố hàn quốc",    "특수여행유형", "먹방여행"),
    ("🇻🇳 Tiếng Việt","hàn quốc mùa đông",             "특수여행유형", "계절여행"),
    ("🇻🇳 Tiếng Việt","lần đầu đi hàn quốc",           "특수여행유형", "첫방문"),
    ("🇹🇭 ภาษาไทย",  "ปั่นจักรยานเกาหลี",               "특수여행유형", "자전거"),
    ("🇹🇭 ภาษาไทย",  "เดินป่าเกาหลี",                   "특수여행유형", "등산/하이킹"),
    ("🇹🇭 ภาษาไทย",  "สตรีทฟู้ดเกาหลี",                 "특수여행유형", "먹방여행"),
    ("🇹🇭 ภาษาไทย",  "เกาหลีหน้าหนาว",                  "특수여행유형", "계절여행"),
    ("🇮🇩 Bahasa Indonesia","bersepeda di korea",       "특수여행유형", "자전거"),
    ("🇮🇩 Bahasa Indonesia","hiking korea",             "특수여행유형", "등산/하이킹"),
    ("🇮🇩 Bahasa Indonesia","street food korea",        "특수여행유형", "먹방여행"),
    ("🇮🇩 Bahasa Indonesia","korea musim dingin",       "특수여행유형", "계절여행"),
    ("🇸🇦 العربية",   "ركوب الدراجة كوريا",             "특수여행유형", "자전거"),
    ("🇸🇦 العربية",   "تسلق جبال كوريا",                "특수여행유형", "등산/하이킹"),
    ("🇸🇦 العربية",   "أكل الشارع كوريا",               "특수여행유형", "먹방여행"),
    ("🇸🇦 العربية",   "كوريا في الشتاء",                "특수여행유형", "계절여행"),
    ("🇹🇷 Türkçe",   "kore bisiklet turu",              "특수여행유형", "자전거"),
    ("🇹🇷 Türkçe",   "kore yürüyüş",                    "특수여행유형", "등산/하이킹"),
    ("🇹🇷 Türkçe",   "kore sokak yemekleri",            "특수여행유형", "먹방여행"),
    ("🇹🇷 Türkçe",   "kore kışın",                      "특수여행유형", "계절여행"),
    ("🇵🇱 Polski",   "rowerem po korei",                "특수여행유형", "자전거"),
    ("🇵🇱 Polski",   "trekking korea",                  "특수여행유형", "등산/하이킹"),
    ("🇵🇱 Polski",   "street food korea",               "특수여행유형", "먹방여행"),
    ("🇵🇱 Polski",   "korea zimą",                      "특수여행유형", "계절여행"),
    ("🇮🇹 Italiano", "bicicletta corea del sud",        "특수여행유형", "자전거"),
    ("🇮🇹 Italiano", "trekking corea",                  "특수여행유형", "등산/하이킹"),
    ("🇮🇹 Italiano", "cibo di strada corea",            "특수여행유형", "먹방여행"),
    ("🇮🇹 Italiano", "corea in inverno",                "특수여행유형", "계절여행"),
    ("🇳🇱 Nederlands","fietsen korea",                  "특수여행유형", "자전거"),
    ("🇳🇱 Nederlands","wandelen korea",                 "특수여행유형", "등산/하이킹"),
    ("🇳🇱 Nederlands","korea winter",                   "특수여행유형", "계절여행"),
    ("🇸🇪 Svenska",  "cykla korea",                     "특수여행유형", "자전거"),
    ("🇸🇪 Svenska",  "vandra korea",                    "특수여행유형", "등산/하이킹"),
    ("🇸🇪 Svenska",  "korea vinter",                    "특수여행유형", "계절여행"),

    # ══════════════════════════════════════════════════════════════
    # 전통 & 문화 체험 (Traditional Culture)
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "taekwondo experience korea",      "전통/문화체험", "태권도"),
    ("🇯🇵 日本語",    "韓国 テコンドー 体験",             "전통/문화체험", "태권도"),
    ("🇨🇳 中文",     "韩国跆拳道体验",                   "전통/문화체험", "태권도"),
    ("🇪🇸 Español",  "experiencia taekwondo corea",     "전통/문화체험", "태권도"),
    ("🇫🇷 Français", "taekwondo en corée",              "전통/문화체험", "태권도"),
    ("🇩🇪 Deutsch",  "taekwondo erfahrung korea",       "전통/문화체험", "태권도"),
    ("🇷🇺 Русский",  "тхэквондо в корее",               "전통/문화체험", "태권도"),
    ("🇺🇸 English",  "hanbok rental seoul",             "전통/문화체험", "한복/한옥"),
    ("🇯🇵 日本語",    "韓服 レンタル",                   "전통/문화체험", "한복/한옥"),
    ("🇨🇳 中文",     "韩服体验",                         "전통/문화체험", "한복/한옥"),
    ("🇪🇸 Español",  "hanbok seúl",                     "전통/문화체험", "한복/한옥"),
    ("🇫🇷 Français", "hanbok séoul",                    "전통/문화체험", "한복/한옥"),
    ("🇩🇪 Deutsch",  "hanbok anprobieren seoul",        "전통/문화체험", "한복/한옥"),
    ("🇷🇺 Русский",  "ханбок сеул",                     "전통/문화체험", "한복/한옥"),
    ("🇺🇸 English",  "korean jjimjilbang vlog",         "전통/문화체험", "찜질방/사우나"),
    ("🇯🇵 日本語",    "韓国 チムジルバン",                "전통/문화체험", "찜질방/사우나"),
    ("🇨🇳 中文",     "韩国汗蒸幕体验",                   "전통/문화체험", "찜질방/사우나"),
    ("🇺🇸 English",  "korean pc bang experience",       "전통/문화체험", "PC방"),
    ("🇯🇵 日本語",    "韓国 PC房 体験",                  "전통/문화체험", "PC방"),
    ("🇺🇸 English",  "korea noraeban karaoke vlog",     "전통/문화체험", "노래방"),
    ("🇺🇸 English",  "korea temple experience vlog",    "전통/문화체험", "사찰/종교"),
    ("🇯🇵 日本語",    "韓国 お寺 体験",                  "전통/문화체험", "사찰/종교"),
    ("🇺🇸 English",  "hiking bukhansan seoul",          "전통/문화체험", "등산/하이킹"),
    ("🇺🇸 English",  "seoraksan hike korea",            "전통/문화체험", "등산/하이킹"),
    ("🇺🇸 English",  "korea paragliding experience",   "전통/문화체험", "이색체험"),
    ("🇺🇸 English",  "korea mud festival foreigner",    "전통/문화체험", "축제"),
    ("🇺🇸 English",  "korea lantern festival vlog",     "전통/문화체험", "축제"),

    # ══════════════════════════════════════════════════════════════
    # K-Food / 음식 체험
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "eating live octopus korea",       "K-Food", "산낙지/해산물"),
    ("🇯🇵 日本語",    "サンナッチ 挑戦 韓国",             "K-Food", "산낙지/해산물"),
    ("🇨🇳 中文",     "韩国吃活章鱼",                     "K-Food", "산낙지/해산물"),
    ("🇪🇸 Español",  "comiendo pulpo vivo corea",       "K-Food", "산낙지/해산물"),
    ("🇫🇷 Français", "manger poulpe vivant corée",      "K-Food", "산낙지/해산물"),
    ("🇩🇪 Deutsch",  "lebenden oktopus essen korea",    "K-Food", "산낙지/해산물"),
    ("🇷🇺 Русский",  "живой осьминог корея",             "K-Food", "산낙지/해산물"),
    ("🇺🇸 English",  "spicy korean food challenge",     "K-Food", "매운음식"),
    ("🇯🇵 日本語",    "韓国 激辛 チャレンジ",             "K-Food", "매운음식"),
    ("🇨🇳 中文",     "挑战韩国辣食",                     "K-Food", "매운음식"),
    ("🇪🇸 Español",  "comida picante coreana",          "K-Food", "매운음식"),
    ("🇫🇷 Français", "défi nourriture épicée corée",    "K-Food", "매운음식"),
    ("🇩🇪 Deutsch",  "scharfes koreanisches essen",     "K-Food", "매운음식"),
    ("🇷🇺 Русский",  "острая корейская еда",            "K-Food", "매운음식"),
    ("🇺🇸 English",  "korean bbq vlog foreigner",       "K-Food", "바베큐/삼겹살"),
    ("🇯🇵 日本語",    "サムギョプサル モッパン",           "K-Food", "바베큐/삼겹살"),
    ("🇨🇳 中文",     "韩国烤肉 vlog",                    "K-Food", "바베큐/삼겹살"),
    ("🇪🇸 Español",  "barbacoa coreana vlog",           "K-Food", "바베큐/삼겹살"),
    ("🇫🇷 Français", "barbecue coréen vlog",            "K-Food", "바베큐/삼겹살"),
    ("🇩🇪 Deutsch",  "koreanisches bbq vlog",           "K-Food", "바베큐/삼겹살"),
    ("🇷🇺 Русский",  "корейское барбекю влог",           "K-Food", "바베큐/삼겹살"),
    ("🇺🇸 English",  "korean street food market tour",  "K-Food", "길거리음식"),
    ("🇯🇵 日本語",    "韓国 屋台飯 食べ歩き",             "K-Food", "길거리음식"),
    ("🇨🇳 中文",     "韩国街头小吃",                     "K-Food", "길거리음식"),
    ("🇺🇸 English",  "korea mukbang foreigner",         "K-Food", "먹방"),
    ("🇯🇵 日本語",    "韓国 モッパン 外国人",             "K-Food", "먹방"),
    ("🇺🇸 English",  "korean convenience store food",   "K-Food", "편의점"),
    ("🇺🇸 English",  "gwangjang market food tour",      "K-Food", "시장"),
    ("🇺🇸 English",  "noryangjin fish market korea",    "K-Food", "시장"),

    # ══════════════════════════════════════════════════════════════
    # K-뷰티 / K-Pop
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "korean skincare clinic vlog",     "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇯🇵 日本語",    "韓国 美容皮膚科 vlog",             "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇨🇳 中文",     "韩国皮肤管理体验",                  "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇪🇸 Español",  "clínica de piel en corea",        "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇫🇷 Français", "clinique de soins coréenne",      "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇩🇪 Deutsch",  "koreanische hautklinik",          "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇷🇺 Русский",  "корейский уход за кожей",         "K-뷰티/K-Pop", "피부과/스킨케어"),
    ("🇺🇸 English",  "korean hair salon transformation","K-뷰티/K-Pop", "미용실"),
    ("🇯🇵 日本語",    "韓国 美容室 イメチェン",           "K-뷰티/K-Pop", "미용실"),
    ("🇨🇳 中文",     "韩国理发店改造",                   "K-뷰티/K-Pop", "미용실"),
    ("🇺🇸 English",  "k-pop idol makeup experience",    "K-뷰티/K-Pop", "아이돌메이크업"),
    ("🇯🇵 日本語",    "韓国 アイドル メイク",             "K-뷰티/K-Pop", "아이돌메이크업"),
    ("🇺🇸 English",  "k-pop locations in seoul",        "K-뷰티/K-Pop", "성지순례"),
    ("🇯🇵 日本語",    "K-POP 聖地巡礼",                  "K-뷰티/K-Pop", "성지순례"),
    ("🇨🇳 中文",     "K-pop打卡首尔",                    "K-뷰티/K-Pop", "성지순례"),
    ("🇪🇸 Español",  "lugares de k-pop seúl",           "K-뷰티/K-Pop", "성지순례"),
    ("🇺🇸 English",  "korea plastic surgery vlog",      "K-뷰티/K-Pop", "성형/시술"),
    ("🇯🇵 日本語",    "韓国 整形 体験 外国人",            "K-뷰티/K-Pop", "성형/시술"),
    ("🇺🇸 English",  "kpop fan meet seoul",             "K-뷰티/K-Pop", "팬미팅/콘서트"),
    ("🇺🇸 English",  "kpop concert experience seoul",   "K-뷰티/K-Pop", "팬미팅/콘서트"),

    # ══════════════════════════════════════════════════════════════
    # 유명인사 내한
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "hollywood actors in korea",       "유명인사", "헐리우드 배우"),
    ("🇯🇵 日本語",    "ハリウッド俳優 韓国訪問",           "유명인사", "헐리우드 배우"),
    ("🇨🇳 中文",     "好莱坞明星在韩国",                  "유명인사", "헐리우드 배우"),
    ("🇺🇸 English",  "celebrities visiting korea",      "유명인사", "해외셀럽"),
    ("🇯🇵 日本語",    "海外セレブ 韓国",                  "유명인사", "해외셀럽"),
    ("🇨🇳 中文",     "欧美明星访韩",                     "유명인사", "해외셀럽"),
    ("🇪🇸 Español",  "famosos en corea del sur",        "유명인사", "해외셀럽"),
    ("🇫🇷 Français", "célébrités en corée",             "유명인사", "해외셀럽"),
    ("🇺🇸 English",  "famous artists in seoul",         "유명인사", "해외아티스트"),
    ("🇺🇸 English",  "foreign politicians in south korea","유명인사","정치인"),

    # ══════════════════════════════════════════════════════════════
    # 일상/거주 (Daily Life / Residents)
    # ══════════════════════════════════════════════════════════════
    ("🇺🇸 English",  "foreign student in korea vlog",   "일상/거주", "유학생"),
    ("🇯🇵 日本語",    "韓国 留学 vlog",                  "일상/거주", "유학생"),
    ("🇨🇳 中文",     "韩国留学日常",                     "일상/거주", "유학생"),
    ("🇪🇸 Español",  "estudiante extranjero en corea",  "일상/거주", "유학생"),
    ("🇫🇷 Français", "étudiant étranger en corée",      "일상/거주", "유학생"),
    ("🇩🇪 Deutsch",  "auslandssemester korea",          "일상/거주", "유학생"),
    ("🇷🇺 Русский",  "учеба в корее влог",              "일상/거주", "유학생"),
    ("🇺🇸 English",  "working in south korea vlog",     "일상/거주", "직장인/워홀"),
    ("🇯🇵 日本語",    "韓国 就職 外国人",                 "일상/거주", "직장인/워홀"),
    ("🇨🇳 中文",     "在韩外国人工作",                   "일상/거주", "직장인/워홀"),
    ("🇺🇸 English",  "amwf couple korea vlog",          "일상/거주", "국제커플"),
    ("🇯🇵 日本語",    "日韓カップル vlog",                "일상/거주", "국제커플"),
    ("🇨🇳 中文",     "异国恋 韩国",                      "일상/거주", "국제커플"),
    ("🇺🇸 English",  "living in a korean apartment",    "일상/거주", "자취/아파트"),
    ("🇯🇵 日本語",    "韓国 ひとり暮らし",                "일상/거주", "자취/아파트"),
    ("🇨🇳 中文",     "韩国独居生活",                     "일상/거주", "자취/아파트"),
    ("🇺🇸 English",  "foreigner daily life seoul",      "일상/거주", "일상브이로그"),
    ("🇺🇸 English",  "expat life korea",                "일상/거주", "일상브이로그"),
    ("🇺🇸 English",  "moving to korea experience",      "일상/거주", "이민/이사"),
    ("🇯🇵 日本語",    "韓国移住 外国人",                  "일상/거주", "이민/이사"),
]

# ── 유틸리티 함수들 ─────────────────────────────────────────────────────────

def get_all_languages() -> list[str]:
    return sorted(set(k[0] for k in KEYWORDS))

def get_all_categories() -> list[str]:
    return sorted(set(k[2] for k in KEYWORDS))

def filter_keywords(langs: list[str] | None = None,
                    categories: list[str] | None = None) -> list[str]:
    result = []
    seen = set()
    for lang, kw, cat, _ in KEYWORDS:
        if langs and lang not in langs:
            continue
        if categories and cat not in categories:
            continue
        if kw not in seen:
            seen.add(kw)
            result.append(kw)
    return result

def keyword_count(langs: list[str] | None = None,
                  categories: list[str] | None = None) -> int:
    return len(filter_keywords(langs, categories))
